// <auto-generated />
namespace DISTRESSUITY.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FeaturedIdea_And_AdLog_Table_Changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeaturedIdea_And_AdLog_Table_Changes));
        
        string IMigrationMetadata.Id
        {
            get { return "201607040951483_FeaturedIdea_And_AdLog_Table_Changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
