// <auto-generated />
namespace DISTRESSUITY.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ConversationReplyChangesRemoveToColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConversationReplyChangesRemoveToColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201606130729334_ConversationReplyChanges Remove To Column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
